/***********************************************************************************************************************
 * Program name :           create_db.sql
 * Description :            Application principale
 * Author :                 Cédric Jankiewicz
 * Creation date :          11.02.2026
 * Modified by :            -
 * Modification date :      -
 * Version :                0.1
 **********************************************************************************************************************/

-- MySQL Script generated by MySQL Workbench
-- Wed Feb 11 15:15:43 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema videogames_platform
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `videogames_platform` ;

-- -----------------------------------------------------
-- Schema videogames_platform
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `videogames_platform` DEFAULT CHARACTER SET utf8 ;
USE `videogames_platform` ;

-- -----------------------------------------------------
-- Table `videogames_platform`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videogames_platform`.`Genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videogames_platform`.`Publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videogames_platform`.`Publishers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videogames_platform`.`Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videogames_platform`.`Games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publisher_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `price` FLOAT(7,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Games_Editor1_idx` (`publisher_id` ASC) VISIBLE,
  CONSTRAINT `fk_Games_Editor1`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `videogames_platform`.`Publishers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videogames_platform`.`DLCs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videogames_platform`.`DLCs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `price` FLOAT(7,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DLC_Games_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_DLC_Games`
    FOREIGN KEY (`game_id`)
    REFERENCES `videogames_platform`.`Games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videogames_platform`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videogames_platform`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videogames_platform`.`Games_has_Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videogames_platform`.`Games_has_Genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Games_has_Genres_Games1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_Games_has_Genres_Genres1_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_Games_has_Genres_Games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `videogames_platform`.`Games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Games_has_Genres_Genres1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `videogames_platform`.`Genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videogames_platform`.`Users_has_Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videogames_platform`.`Users_has_Games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_has_Games_Users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Games_Games1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Games_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `videogames_platform`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Games_Games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `videogames_platform`.`Games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videogames_platform`.`Users_has_DLCs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videogames_platform`.`Users_has_DLCs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `DLC_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_has_DLC_DLC1_idx` (`DLC_id` ASC) VISIBLE,
  INDEX `fk_Users_has_DLC_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_DLC_DLC1`
    FOREIGN KEY (`DLC_id`)
    REFERENCES `videogames_platform`.`DLCs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_DLC_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `videogames_platform`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
